context:
  name: shs-cxi-drivers
  version: "14.0.1"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/HewlettPackard/shs-cxi-driver/archive/refs/tags/release/shs-${{ version }}.tar.gz
  sha256: 3f197a1ab91156af0b71ddd9fbfadf9cff96092e046973c535a6a358d49cfa7e

build:
  number: 0
  noarch: generic
  script: build.sh

tests:
  - script:
      - test -f $PREFIX/include/linux/hpe/cxi/cxi.h
      - test -f $PREFIX/include/uapi/misc/cxi.h

about:
  homepage: https://github.com/HewlettPackard/shs-cxi-driver
  repository: https://github.com/HewlettPackard/shs-cxi-driver
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: 'Headers for CXI drivers'
  description: |
    Provides UAPI headers for CXI (Cassini eXtended Interface) drivers.
    Licensed under GPL-2.0-or-later as per COPYING file and cray-cxi-driver.spec.

extra:
  recipe-maintainers:
    - j34ni
